### ISSUE TITLE
Setting Global up top doesn't do anything

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#389]
### What's your issue about?

If you set a global at the top of a viper source file (outside of any contract methods), nothing changes and no exception or warning is raised.

```bash
(viper)$ cat test*.v.py
# test-false.v.py
test: bool = false

def toggle():
    self.test = not self.test

# test-true.v.py
test: bool = true

def toggle():
    self.test = not self.test

(viper)$ diff <(./bin/viper test-false.v.py) <(./bin/viper test-true.v.py)
(viper)$ # No difference
```
### How can it be fixed?

Two options, either that syntax fails:
```python
import pytest
from pytest import raises
from viper import compiler

def test_global_setter():
    bad_code = """
switch: public(bool) = false

def toggle():
    self.switch = not self.switch
"""
    with raises(Exception):
        # Fails due to setting global outside of method
        compiler.compile(bad_code)
```

Or the syntax is allowed and somehow sets the initial state:
```python
import pytest
from .setup_transaction_tests import get_contract

def test_block_number():
    notset_code = """
switch: public(bool)

def toggle():
    self.switch = not self.switch
"""
    false_code = """
switch: public(bool) = false

def toggle():
    self.switch = not self.switch
"""

    true_code = """
switch: public(bool) = true

def toggle():
    self.switch = not self.switch
"""
    # All three compile
    cn = get_contract(notset_code)
    cf = get_contract(false_code)
    ct = get_contract(true_code)

    # Toggling works
    assert cn.get_switch() == cf.get_switch()
    cn.toggle()
    assert cn.get_switch() != cf.get_switch()
    cf.toggle()
    assert cn.get_switch() and cf.get_switch()
    assert cn.get_switch() == cf.get_switch()

    # cf.switch is true at this point
    # This doesn't work as expected (fails)
    assert ct.get_switch() == cf.get_switch()
    ct.toggle()
    # But this works
    assert ct.get_switch() == cf.get_switch()
```

#### Cute Animal Picture

![aardvark](https://assets3.thrillist.com/v1/image/2509330/size/tmg-article_tall;jpeg_quality=20.jpg)

**Comment by DavidKnott** [comment]
@fubuloubu I think global assignment at the top increases readability and should be implemented.  What do you think?

**Comment by fubuloubu** [comment]
You mean like make it mandatory? Well, behind the scenes for certain types (namely maps) it's all zeros, and we wouldn't have any control over that. For integer types and boolean flags, I think having the option is nice but not mandatory. But for constants/macros I think it should be mandatory.

**Comment by DavidKnott** [comment]
@fubuloubu Just tried it out and this issue has been fixed, closing.

**Comment by fubuloubu** [comment]
@DavidKnott cool, setting a mapping still doesn't do anything, right?
